language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
jdk:
- oraclejdk8
branches:
  only:
  - master
script: "./travis-build.sh"
env:
  matrix:
  - secure: vgbOBLL/6aW4u5CXsjO5rNwqXTwr5qLxAUTfz+ymZ3e+xepiFGWs69FBOMyY7UmERzGaM3iFj5w8/BZLxMfXjHF1W5Km4Zyd1+1hwe72yKrH5SAAkXHSuAAfxkFFTcqwm5MxLOKWVwmup4hI1U/SCtJT8bCETHzLhYzFWsoLqQGPPFgk03L/7k7F6FBdTDi7ziv5J6AOvl25JpdG8JQ2c0RMbXE9RsbTfSH22l6FnljPJ2mntnQNtba8ds6xii0gO7Rpjis2bob/N5FbHW7QqwxRGnAcJO+u6cZJ2Ll+VA1xDSIVleF4oHho0gVyt16YjCYDzgKo2w9II89FtMCoE21DhnvquBtbXTRIHJwX+gBUoBp5AFNjroORf7P0mrDqBfyeuet6L1eo1FsqIDL/OAsMtLgtDx4Sb7nH1vYUYE6d48vaejhN0IzzXl4Uf7hkfYc2JJdBDWhp1F2q6lPBQO2QSbDrRkbpQbJ+MG1zMSyLpTuoD9uOv4eOKyZogmLUtekHakHNtTniWELADcwpNlCf1jIQePEKZrTw/GGlRP7jjGw+JzfTXKOTzlBJburXblHsHjapbB9C3EttAErXbaKLrfi0CxBvF/o0OVywGNHXDXP849ctHrYOvqEFk505cJnpDMVkloRZ0vHc4eOyaw9UiJHWyeSproMbWDHYVkU=
  - secure: QA2hsh7U1i2sLi11VwZQEOtwcq3+iPUh27dNI52Wt/C7DPWdFwOzceBsGIbXrdbX3ja5BeDJXI3d8g4K1CGVuFcTgg7qi7VvKo5yJt8H8raSrPuFwlQvC6kJOaXYVCm08rqFLiv3Ccq2jdE1TeO9Ncu84y3YlJBJo4Z9D8Rmg2pJMZof2cmp8WbzLHgac2fWflJvp4FYkL95z+65AVJX2SL7yEyuKCLF5JZ3ipLVnRggNxuTMCA0Jrh1gdo2P6g8O8OTdWMSDCapwmzqX1+DMuBq6wElkX3J2ThyxmkVDGlvmo+6PnBI7z9s/FQp4JtiwyizizYx9T7gzGiRrVzhbrVdqNntR4kNqhwkAN56V7dc85HqNpKf8KekLnOQCSd3bBqqjqg8F8QllUsv8hEeuSJ0EnSwYaZQN8XaG3NrnAyfH7svSeCK/K+36x45lB6Aa0pmFNV8lV8oNPRNCkw0UKhPLQdhfEvFQXoZMDM757TcVOvl8Jy1GaL0oqtWVgcdF5qyXyEkCwMsqsHMhrHRuLYfhmW7ADq3GIr1igBowL2OiTWtDxuYYnyH1bjKL2oTbC0MMxWE0xuZ6ZpihIbSbeo2vJEGviLG5q+m+OkqTxS3SLj0WmrSxLOiDY5TOclrooENnA3i3xEWofk1/+fS6T4U6+MMhH+WDNEafVhpcdc=
